### ISSUE TITLE
Support CW1155 

### ISSUE THREAD

**Issue by javiersuweijie** [mars-protocol/cw-asset#10]
Other than native and cw20. It would be good to support [CW1155 multi-token contracts](https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw1155-base). 

A CW1155 tokens consists of a `contract_addr: Addr` and a `token_id: String`

It could look something like:
```
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AssetInfoBase<T> {
    Cw20(T),
    Cw1155(T, String),
    Native(String),
}
```

**Comment by larry0x** [comment]
implemented in #11, thank you!
