### ISSUE TITLE
Update cw dependencies from 0.13 to 016

### ISSUE THREAD

**Issue by apollo-pablo** [mars-protocol/cw-asset#19]
Hi!

cw dependencies are getting old, could it be possible to update them from 0.13 to 0.16 on `Cargo.toml`?

Thanks!

**Comment by larry0x** [comment]
Yes will do a bit later today

**Comment by larry0x** [comment]
done, i will publish to crates.io shortly: https://github.com/mars-protocol/cw-asset/releases/tag/v2.4.0
